apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v2
  template:
    metadata:
      labels:
        app: backend-v2
    spec:
      containers:
      - name: backend-v2
        image: <your-backend-v2-image>
        ports:
        - containerPort: 80
---

