apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-v1
  template:
    metadata:
      labels:
        app: backend-v1
    spec:
      containers:
      - name: backend-v1
        image: <your-backend-v1-image>
        ports:
        - containerPort: 80
---

